### ISSUE TITLE
Environment Variables are not respected

### ISSUE THREAD

**Issue by MrMysterius** [dicedtomatoreal/typex#177]
Some or all of my environment variables are not respected or used.

The `CORE_HTTPS` is not getting used or always defaults to `false`, because I always get back URLs only with `http` not `https`.
As well are the `DISCORD_XX` variables don't seem to work since I'm not getting any messages/events send through the webhook.

The Zipline Part of my `docker-compose.yml` is this:

```yaml
zipline:
  image: ghcr.io/diced/zipline
  ports:
    - '10.10.10.100:9200:3000'
  restart: always
  environment:
    CORE_HTTPS: true
    CORE_SECRET: REDACTED
    CORE_HOST: 0.0.0.0
    CORE_PORT: 3000
    CORE_DATABASE_URL: REDACTED
    CORE_LOGGER: true
    UPLOADER_ROUTE: /f
    URLS_LENGTH: 6
    URLS_ROUTE: /s
    DISCORD_URL: "REDACTED"
    DISCORD_UPLOAD: "[:page_facing_up: {file.created_at.full_string}] {user.name} - {link}"
    DISCORD_SHORTEN: "[:link: {url.created_at.full_string}] {user.name} - {link}"
  volumes:
    - './uploads:/zipline/uploads'
    - './public:/zipline/public'
  depends_on:
    - 'postgres'
```

**Comment by NebulaBC** [comment]
I've had the same exact issue with CORE_HTTPS, I think this is less an issue of all ENV but just those in specific.
(for now I just modified my screenshot script to `sed -En 's/http/https/p'`, if you use a script and not sharex I would recommend this as a work around)

**Comment by MrMysterius** [comment]
Sorry @NebulaBC, but I use ShareX, maybe I can get a little workaround there too.
Should still be fixed.

**Comment by NebulaBC** [comment]
I'm sure that diced has it on his radar. You know how those things go though. The waiting game

**Comment by MrMysterius** [comment]
Probably Found The HTTPS Issue:
https://github.com/diced/zipline/blob/bd055d704b4716d4d1ff43298b51af759c47e685/src/lib/config/validateConfig.ts#L19

This should probably say `https: boolean().default(false),` like in the lines around it:
https://github.com/diced/zipline/blob/bd055d704b4716d4d1ff43298b51af759c47e685/src/lib/config/validateConfig.ts#L11-L13
https://github.com/diced/zipline/blob/bd055d704b4716d4d1ff43298b51af759c47e685/src/lib/config/validateConfig.ts#L24

Because this is not the case, it will always default back to false.

**Comment by MrMysterius** [comment]
Also, these Discord Environment Variables are not even used/exists (`DISCORD_UPLOAD` and `DISCORD_SHORTEN`):

![image](https://user-images.githubusercontent.com/25854814/192391622-1aff7445-63ce-416b-b488-351374ec3292.png)
> Source: https://zipline.diced.tech/docs/guides/discord-webhooks

Changing these variables from this:

> ```yaml
> DISCORD_UPLOAD: "[:page_facing_up: {file.created_at.full_string}] {user.name} - {link}"
> DISCORD_SHORTEN: "[:link: {url.created_at.full_string}] {user.name} - {link}"
> ```

to this:

```yaml
DISCORD_UPLOAD_CONTENT: "[:page_facing_up: {file.created_at.full_string}] {user.name} - {link}"
DISCORD_SHORTEN_CONTENT: "[:link: {url.created_at.full_string}] {user.name} - {link}"
```

Fixed the issue. Please remove the entries with `DISCORD_UPLOAD` and `DISCORD_SHORTEN` from the docs, or make more clear that these are not the correct ones.

**Comment by diced** [comment]
> This should probably say https: boolean().default(false), like in the lines around it:

`bool()` is the same thing as `boolean()` but I will probably just change it to boolean() so everything is the same.

> Also, these Discord Environment Variables are not even used/exists (DISCORD_UPLOAD and DISCORD_SHORTEN):

This will be fixed when I release the next version of Zipline (docs will be updated at the same time)

I'm unsure as to why CORE_HTTPS still doesn't work, as when I have been testing it, it just works and returns a HTTPS link. I do not know if this is the problem but the way you have your environment stuff set up is kind of different from what I have in the example docker files.

A troubleshooting step I'd advise doing is running `yarn scripts:read-config`, it'll return a JSON representation of the config and you can check if `core.https` is true or false. If this is false even though you have it as true then I'd try changing the way its formatted in the docker-compose.yml to the way it is in my example files.

**Comment by MrMysterius** [comment]
> but the way you have your environment stuff set up is kind of different from what I have in the example docker files.

Works the same. Did try it the other way around before as well.

Thanks for the way of troubleshooting.

> bool() is the same thing as boolean() but I will probably just change it to boolean() so everything is the same.

Also, fix seems to work.
